export const MIN_RESERVATION_HOURS = 1;
export const MAX_RESERVATION_HOURS = 12;
export const MIN_RESERVATION_MS = MIN_RESERVATION_HOURS * 60 * 60 * 1000;
export const MAX_RESERVATION_MS = MAX_RESERVATION_HOURS * 60 * 60 * 1000;
